cheeses/urls.py
from django.urls import path
# import from project
from .import views


app_name = "cheeses"

urlpatterns = [
	path(route='', view=views.CheeseListView.as_view(), name='list'),
	path(route='add/', view=views.CheeseCreateView.as_view(), name='add'),
	path(route='<slug:slug>/', view=views.CheeseDetailView.as_view(), name='detail'),
	path(route='<slug:slug>/update/', view=views.CheeseUpdateView.as_view(), name='update'),

]

everycheese2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('cheeses/', include('cheeses.urls', namespace='cheeses')),
]

users/urls.py
from django.urls import path
# Import from project
from .views import index

app_name = 'users'

urlpatterns = [
    path('', index, name='index'),
]

cheeses/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
# Third Party Packages
from model_utils.models import TimeStampedModel
from autoslug import AutoSlugField
from django_countries.fields import CountryField




# TimeStampedModel automatically gives the model created and modified fields, 
# which automatically track when the object is created or modified.

class Cheese(TimeStampedModel):

	# Choices selection
	class Firmness(models.TextChoices):
		UNSPECIFIED = "unspecified", "Unspecified"
		SOFT = "soft", "Soft"
		SEMI_SOFT = "semi-soft", "Semi Soft"
		HARD = "hard", "Hard"


	name = models.CharField("Name of Cheese", max_length=255)
	slug = AutoSlugField("Cheese Address", unique=True, always_update=False, populate_from="name")
	description = models.TextField("Description", blank=True)
	firmness = models.CharField("Firmness", max_length=20, choices=Firmness.choices, default=Firmness.UNSPECIFIED)
	country_of_origin = CountryField("Country of Origin", blank=True)
	creater = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)

	def get_absolute_url(self):
		"""
			This can be used to redirect user from cheese add page to detail page. 
			Then we need not to define success_url in CheeseCreateView view.
			Return absolute URL to the Cheese Detail page.
		"""
		return reverse('cheeses:detail', kwargs={"slug": self.slug})

	def __str__(self):
		return self.name

users/models.py
from django.db import models

# Create your models here.

cheeses/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
# import from project
from .models import Cheese


class CheeseListView(ListView):
	model = Cheese


class CheeseDetailView(DetailView):
	model = Cheese
	template_name = "cheeses/my_cheese_detail.html"
	context_object_name = 'mycheese'


class CheeseCreateView(LoginRequiredMixin, CreateView):
	model = Cheese
	fields = ['name', 'description', 'firmness', 'country_of_origin', ]
	template_name = "cheeses/add.html"

	def form_valid(self, form):
		form.instance.creator = self.request.user
		return super().form_valid(form)


class CheeseUpdateView(LoginRequiredMixin, UpdateView):
	model = Cheese
	fields = ['name', 'description', 'firmness', 'country_of_origin']
	action = 'Update'
	template_name = "cheeses/add.html"

users/views.py
from django.shortcuts import render



def index(request):
	return render(request, 'users/index.html')	

templates/cheeses/add.html
{% load crispy_forms_tags %}
{% with action=view.action|default:"Add" %}

<h1>Add Cheese</h1>

<form method="post" action=".">
	{% csrf_token %}
	{{ form|crispy }}
	<button  type="submit">{{ action }}</button>	
</form>

{% endwith %}

templates/cheeses/cheese_list.html
<a href="{% url 'cheeses:add' %}">Add Cheese</a>
<ul>
	{% for cheese in cheese_list %}
		<li><a href="{% url 'cheeses:detail' cheese.slug %}">{{ cheese.name }}</a> </li>
	{% endfor %}
</ul>

templates/cheeses/my_cheese_detail.html
<h2>{{ mycheese.name }}</h2>

	{% if mycheese.firmness %}
		<p>Firmness: {{ mycheese.get_firmness_display }}</p>
	{% endif %}

	{% if mycheese.description %}
		<p>{{ mycheese.description }}</p>
	{% endif %}

	{% if mycheese.country_of_origin %}
		<p>
			Country of Origin: {{ mycheese.country_of_origin.name }}
			<img src="{{ mycheese.country_of_origin.flag }}" />
		</p>
	{% endif %}

	<p>
		<a href="{% url 'cheeses:update' mycheese.slug %}">Update</a>
	</p>

templates/users/index.html
<h1> From users</h1>